[project]
name = "asteroids-game"
version = "0.1.0"
description = "Asteroids game built with pygame"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame==2.6.1",
]

[tool.poetry.scripts]
asteroids = "src.game.main:main"